config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get '/users/sign_out' => 'main#index'
  end
  resources :handymen
  resources :customers
  resources :shops
  resources :admins
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root 'main#index'
end

app/views/admins/_form.html.erb
<div class="container">
  <%= form_for @admin do |f| %>
    <% if @admin.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this @admin from being saved:</h2>

        <ul>
        <% @admin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.label :admin %>
      <%= f.fields_for :user do |user| %>
        <div class="form-group">
          <%= user.label :first_name %>
          <%= user.text_field :first_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= user.label :last_name %>
          <%= user.text_field :last_name %>
        </div>
        <div class="form-group">
          <%= user.label :country %>
          <%= user.text_field :country %>
        </div>
        <div class="form-group">
          <%= user.label :city %>
          <%= user.text_field :city %>
        </div>
        <div class="form-group">
          <%= user.label :street_address %>
          <%= user.text_field :street_address %>
        </div>
        <div class="form-group">
          <%= user.label :email %>
          <%= user.text_field :email %>
        </div>
        <div class="form-group">
          <%= user.label :phone_number %>
          <%= user.text_field :phone_number %>
        </div>

      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admins</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>
<%=  @admin.user.first_name%>
<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>